language: php

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer install --no-interaction

before_script:
  - mkdir -p src-tests/logs/
  - mkdir -p src-tests/coverage/

script:
  - cd src-tests && ../vendor/bin/phpunit --coverage-clover ./logs/clover.xml
  - cd .. && vendor/bin/phpcs --standard=ruleset.xml

after_script:
  - vendor/bin/coveralls -v -c .coveralls.yml
